### PR TITLE
added diploid test functions

### PR DESCRIPTION
**Pull request by astheeggeggs**
## Adding diploid tree functionality - tests first!

A series of tests to check that tree based forwards, backwards and viterbi work, by comparing to matrix based implementation in lshmm in pypi.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Any idea what's happening here @benjeffery? We seem to be getting unrelated errors in the metadata tests after we pull in the lshmm module (which only depends on numba). Is there something obscure happening here with numpy versions or something?

**Comment by benjeffery** [comment]
> Any idea what's happening here @benjeffery? We seem to be getting unrelated errors in the metadata tests after we pull in the lshmm module (which only depends on numba). Is there something obscure happening here with numpy versions or something?

I believe it's this https://github.com/tskit-dev/tskit/issues/2481

**Comment by astheeggeggs** [comment]
Tests now all pass. On the other branch I pinned jsonschema in various requirements files, but the one that seems to count is `python/requirements/CI-tests-conda/requirements.txt`.

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by jeromekelleher** [comment]
@Mergifyio rebase

**Review by jeromekelleher — APPROVED** [review]

**Comment by jeromekelleher** [comment]
We need a pin on jsonschema to get this to pass I think, and probably better to do that separately (#2481)

**Comment by benjeffery** [comment]
> We need a pin on jsonschema to get this to pass I think, and probably better to do that separately (#2481)

Yep, just working on this. Looks like an unpinned jsonschema is bought in by conda, so will pin there.

**Comment by jeromekelleher** [comment]
@Mergifyio rebase

**Pull request merged**
