### PR TITLE
Negative indexing

### LINKED ISSUE #1008: Negative table indexing
It's often useful to check the last provenance. We should support `ts.provenance(-1)`

### PR DESCRIPTION
**Pull request by hyanwong**
## Description

Fixes #1008

How should I do the tests? It looks like the containers are all tested using the `SimpleContainersMixin`, so I guess I should add something to that to text for negative indexes. But I'm not sure how the mixing stuff works, TBH.

# PR Checklist:

- [x] Tests that fully cover new/changed functionality.
- [x] Documentation including tutorial content if appropriate.
- [x] Changelogs, if there are API changes.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Hmm, tricky one. Let's take a chance to think this one through so we're sure there's no unintended consequences.

I think we should probably do it for actual tables also if we do it for the ts accessors, but we could log that as a follow up issue required for the next release.

What do you think @benjeffery?

**Comment by benjeffery** [comment]
> What do you think @benjeffery?

Yes, better to do the tables as a separate issue. I've been trying to think of adverse consequences, the only thing I can think is that -ve indexing can hide bugs in index calculation - but it is a standard Python thing.

**Comment by jeromekelleher** [comment]
Yeah - I don't think we can break anyone's code, unless they are depending on us throwing an error on a negative index right?

**Comment by benjeffery** [comment]
> Yeah - I don't think we can break anyone's code, unless they are depending on us throwing an error on a negative index right?

Yes, that would be the only case - not impossible that someone has done that. Strictly speaking, this is a breaking change.

**Comment by jeromekelleher** [comment]
Seems fine then once we highlight it as such in the release notes.

**Comment by hyanwong** [comment]
> Seems fine then once we highlight it as such in the release notes.

it looks like the approach is OK then. Can someone (e.g. @benjeffery ) give me pointers about my question below:

> How should I do the tests? It looks like the containers are all tested using the SimpleContainersMixin, so I guess I should add something to that to text for negative indexes. But I'm not sure how the mixing stuff works, TBH.

**Comment by benjeffery** [comment]
`SimpleContainersMixin` tests the containers returned by the row accessors.

Something like this added to `TestTreeSequence`:
```python
@pytest.mark.parametrize("ts", get_example_tree_sequences())
    def test_row_getter(self, ts):
        for table_name in ts.tables_dict.keys():
            sequence = getattr(ts, table_name)()
            length = getattr(ts, "num_" + table_name)
            for i, n in enumerate(sequence):
                assert i == n.id
                assert getattr(ts, table_name[:-1])(i) == n
                assert getattr(ts, table_name[:-1])(-(length-i)) == n
```
Haven't tested this though!

**Comment by hyanwong** [comment]
Thanks for the testing code @benjeffery - ready for review.

**Review by benjeffery — COMMENTED** [review]
Are there tests not visible in the diff for things like floating point, numpy ints, `None` and other oddities?

**Comment by hyanwong** [comment]
> Are there tests not visible in the diff for things like floating point, numpy ints, `None` and other oddities?

Hmm, good point. I don't think those were ever tested, TBH. We just assumed that they would be dealt with by the default  python indexing stuff. I could add specific tests.

**Comment by hyanwong** [comment]
> > Are there tests not visible in the diff for things like floating point, numpy ints, `None` and other oddities?
> 
> Hmm, good point. I don't think those were ever tested, TBH. We just assumed that they would be dealt with by the default python indexing stuff. I could add specific tests.

There are some tests in `test_lowlevel.py` for `get_individuals(id)` etc, but they only seem to test the integer bounds:

https://github.com/tskit-dev/tskit/blob/22d57fb080200cac60ae29970a4aadea2dcc86ec/python/tests/test_lowlevel.py#L2804

**Comment by benjeffery** [comment]
Yeah, best to add a few. We've had weird things happen before!

**Comment by hyanwong** [comment]
Best to add in low-level or highlevel? I guess in the same place as the existing tests (i.e. high-level, but in test_tables.py)

**Comment by hyanwong** [comment]
> (i.e. high-level, but in test_tables.py)

Sorry, was getting my PRs in a twist. I meant highlevel.py

**Comment by benjeffery** [comment]
Yep in `highlevel.py`.

**Comment by hyanwong** [comment]
Do we have a simple ts for testing this sort of thing. No point doing it over all the `get_example_tree_sequences()`. Or I could do it with an empty TS.

**Comment by hyanwong** [comment]
> Do we have a simple ts fixture for testing this sort of thing. No point doing it over all the `get_example_tree_sequences()`. Or I could do it with an empty TS.

Ah, got it: `simple_degree2_ts_fixture`

**Comment by hyanwong** [comment]
Added, and raised an explicit error to match python indexing

**Review by benjeffery — APPROVED** [review]
Great, thanks @hyanwong!

**Comment by hyanwong** [comment]
Thanks @benjeffery . You said:

> Yes, better to do the tables as a separate issue.

But I think we can already do `ts.tables.edges[-1]`, so I think we are all done here, no?

**Comment by benjeffery** [comment]
Yep! Thanks!

**Pull request merged**
