### PR TITLE
adding forwards backwards testing

### PR DESCRIPTION
**Pull request by astheeggeggs**
## Added test functions to run diploid forwards-backwards Li and Stephens

This suite of tests implements a python tree-based implementation of diploid Li and Stephens, and compares to a matrix based implementation for testings.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks like we still have 0.2.0 deps in there, do a grep for lshmm in ``requirements/``

**Comment by astheeggeggs** [comment]
> 

Mopped up the last one

**Comment by benjeffery** [comment]
Wow, this is odd. I've done a different PR with the same code (https://github.com/tskit-dev/tskit/pull/2504) and it passes. I'm going to add a commit here to reset the CI cache, hopefully that will clear this failure.

**Comment by benjeffery** [comment]
Well, that seems to have done the trick.

giphy

**Comment by jeromekelleher** [comment]
OK, ready to merge after another squash?

**Review by jeromekelleher — APPROVED** [review]

**Comment by benjeffery** [comment]
Error looks transient, retrying.

**Pull request merged**
