### PR TITLE
add seeds and extra check in python implementation

### LINKED ISSUE #988: Flakey test "TestNodeTraitRegression.test_wright_fisher_unsimplified"
I've seen this test fail on CI at a rate of a couple a week.
```
 =================================== FAILURES ===================================
 ___________ TestNodeTraitRegression.test_wright_fisher_unsimplified ____________
 [gw1] darwin -- Python 3.6.11 /usr/local/miniconda/envs/anaconda-client-env/bin/python3.6
 
 self = <tests.test_tree_stats.TestNodeTraitRegression object at 0x7fe6c4bda048>
 
     def test_wright_fisher_unsimplified(self):
         tables = wf.wf_sim(
             4,
             5,
             seed=1,
             deep_history=True,
             initial_generation_samples=False,
             num_loci=5,
         )
         tables.sort()
         ts = tables.tree_sequence()
 >       self.verify(ts)
 
 tests/test_tree_stats.py:594: 
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
 tests/test_tree_stats.py:4488: in verify
     self.verify_trait_regression(ts, W, Z, windows=windows)
 tests/test_tree_stats.py:4546: in verify_trait_regression
     self.assertArrayAlmostEqual(sigma1, sigma3)
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
 
 self = <tests.test_tree_stats.TestNodeTraitRegression object at 0x7fe6c4bda048>
 x = array([[[0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         ...65014],
         [0.        ],
         [0.2617744 ],
         [0.        ],
         [0.        ],
         [0.19294995]]])
 y = array([[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
       ...[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]])
 atol = 1e-06, rtol = 1e-07
 
     def assertArrayAlmostEqual(self, x, y, atol=1e-6, rtol=1e-7):
 >       nt.assert_allclose(x, y, atol=atol, rtol=rtol)
 E       AssertionError: 
 E       Not equal to tolerance rtol=1e-07, atol=1e-06
 E       
 E       Mismatched elements: 103 / 315 (32.7%)
 E       Max absolute difference: 0.26177442
 E       Max relative difference: inf
 E        x: array([[[0.      ],
 E               [0.      ],
 E               [0.      ],...
 E        y: array([[[0.],
 E               [0.],
 E               [0.],...
 
 tests/test_tree_stats.py:541: AssertionError
```

### PR DESCRIPTION
**Pull request by petrelharp**
Closes #988 (I hope), both by setting the seed but also doing the same numerical tolerance check in python as in C.

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/tskit-docs/991/)

**Comment by petrelharp** [comment]
I'd say we should do like #989 with this, except that it should just be doing the same thing over and over again...

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Review by benjeffery — APPROVED** [review]
Thanks! LGTM!

**Pull request merged**
