### PR TITLE
Put record_provenance in table.simplify

### LINKED ISSUE #374: How to make simplify() consistent between tree seqs & tables?
At the moment, `tables.simplify()` does not take a `record_provenance` parameter. It should. However, `ts.simplify()` *does* take such a parameter, as the penultimate one (before the `keep_unary` argument).

If we add this param as the last param of `tables.simplify()`, it breaks less code, but it means that the tree_sequence and tables versions have parameters in different orders, which is *horrible*.

There's no easy solution here that I can see. My preferred option is for `ts.simplify()` to match the other tree sequence methods and have `record_provenance` as the last parameter, but that's a breaking change.

Suggestions?

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #374. Also places deprecated aliases at end of the argument list

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Comment by benjeffery** [comment]
@hyanwong Do we have an issue for the ongoing work that is marked as TODO in this PR?

**Comment by hyanwong** [comment]
You mean the provenance stuff? It's all full of TODOs like this (I'm just copying the other methods here). I made a rough PR at https://github.com/tskit-dev/tskit/pull/243 (but then left it for you to do properly :) ) and there's a minimally descriptive PR at https://github.com/tskit-dev/tskit/issues/31 .

**Comment by benjeffery** [comment]
Ah cool! I'll pick that up soon, need to do a wave of provenance work to flesh out the API.

**Comment by hyanwong** [comment]
Yep. It would be helpful, if possible, to provide a generic way of doing this. E.g. in tsinfer we want to record provenance by accessing the command name and parameters, and currently we are omitting the parameters ( https://github.com/tskit-dev/tsinfer/issues/332 )

**Comment by hyanwong** [comment]
Also, I've taken the (non-executive) decision to place deprecated-but-documented parameters at the end of the parameter list, as long as it is possible to change their position without changing the behaviour (i.e. if they are keyword-only anyway). I guess that's OK @benjeffery & @jeromekelleher ?

**Comment by benjeffery** [comment]
> Also, I've taken the (non-executive) decision to place deprecated-but-documented parameters at the end of the parameter list, as long as it is possible to change their position without changing the behaviour (i.e. if they are keyword-only anyway). I guess that's OK @benjeffery & @jeromekelleher ?

Yep, if it doesn't break anything like you say I agree.

**Pull request merged**
