### PR TITLE
Move testlib global definitions out of header.

### LINKED ISSUE #817: c tests fail to build
```
$ meson build
The Meson build system
Version: 0.54.3
Source dir: /home/grg/src/tskit/c
Build dir: /home/grg/src/tskit/c/build
Build type: native build
Project name: tskit
Project version: undefined
C compiler for the host machine: cc (gcc 10.1.0 "cc (GCC) 10.1.0")
C linker for the host machine: cc ld.bfd 2.34.0
C++ compiler for the host machine: c++ (gcc 10.1.0 "c++ (GCC) 10.1.0")
C++ linker for the host machine: c++ ld.bfd 2.34.0
Host machine cpu family: x86_64
Host machine cpu: x86_64

|Executing subproject kastore method meson
|
|Project name: kastore
|Project version: undefined
|C compiler for the host machine: cc (gcc 10.1.0 "cc (GCC) 10.1.0")
|C linker for the host machine: cc ld.bfd 2.34.0
|C++ compiler for the host machine: c++ (gcc 10.1.0 "c++ (GCC) 10.1.0")
|C++ linker for the host machine: c++ ld.bfd 2.34.0
|Build targets in project: 1
|Subproject kastore finished.

Library m found: YES
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency cunit found: YES 2.1-3
Build targets in project: 21

tskit undefined

  Subprojects
    kastore: YES

Found ninja-1.10.0.git.kitware.jobserver-1 at /home/grg/.local/bin/ninja
Generating targets:   0%|                                                    | 0/21 [00:00<?,                                                                                               Writing build.ninja:   0%|                                                   | 0/82 [00:00<?, 
```

```
$ ninja -C build
ninja: Entering directory `build'
[32/55] Linking target test_core
FAILED: test_core
cc  -o test_core 'test_core@exe/tests_test_core.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group libtskit.a subprojects/kastore/libkastore.a libtestlib.a -lm /usr/lib/libcunit.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/:$ORIGIN/subprojects/kastore' -Wl,-rpath-link,/home/grg/src/tskit/c/build/ -Wl,-rpath-link,/home/grg/src/tskit/c/build/subprojects/kastore
/usr/bin/ld: libtestlib.a(tests_testlib.c.o):/home/grg/src/tskit/c/build/../tests/testlib.h:39: multiple definition of `_tmp_file_name'; test_core@exe/tests_test_core.c.o:/home/grg/src/tskit/c/build/../tests/testlib.h:39: first defined here
/usr/bin/ld: libtestlib.a(tests_testlib.c.o):/home/grg/src/tskit/c/build/../tests/testlib.h:40: multiple definition of `_devnull'; test_core@exe/tests_test_core.c.o:/home/grg/src/tskit/c/build/../tests/testlib.h:40: first defined here
collect2: error: ld returned 1 exit status
[33/55] Linking target test_stats
FAILED: test_stats
cc  -o test_stats 'test_stats@exe/tests_test_stats.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group libtskit.a subprojects/kastore/libkastore.a libtestlib.a -lm /usr/lib/libcunit.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/:$ORIGIN/subprojects/kastore' -Wl,-rpath-link,/home/grg/src/tskit/c/build/ -Wl,-rpath-link,/home/grg/src/tskit/c/build/subprojects/kastore
/usr/bin/ld: libtestlib.a(tests_testlib.c.o):/home/grg/src/tskit/c/build/../tests/testlib.h:39: multiple definition of `_tmp_file_name'; test_stats@exe/tests_test_stats.c.o:/home/grg/src/tskit/c/build/../tests/testlib.h:39: first defined here
/usr/bin/ld: libtestlib.a(tests_testlib.c.o):/home/grg/src/tskit/c/build/../tests/testlib.h:40: multiple definition of `_devnull'; test_stats@exe/tests_test_stats.c.o:/home/grg/src/tskit/c/build/../tests/testlib.h:40: first defined here
collect2: error: ld returned 1 exit status
[35/55] Linking target test_genotypes
FAILED: test_genotypes
cc  -o test_genotypes 'test_genotypes@exe/tests_test_genotypes.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group libtskit.a subprojects/kastore/libkastore.a libtestlib.a -lm /usr/lib/libcunit.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/:$ORIGIN/subprojects/kastore' -Wl,-rpath-link,/home/grg/src/tskit/c/build/ -Wl,-rpath-link,/home/grg/src/tskit/c/build/subprojects/kastore
/usr/bin/ld: libtestlib.a(tests_testlib.c.o):/home/grg/src/tskit/c/build/../tests/testlib.h:39: multiple definition of `_tmp_file_name'; test_genotypes@exe/tests_test_genotypes.c.o:/home/grg/src/tskit/c/build/../tests/testlib.h:39: first defined here
/usr/bin/ld: libtestlib.a(tests_testlib.c.o):/home/grg/src/tskit/c/build/../tests/testlib.h:40: multiple definition of `_devnull'; test_genotypes@exe/tests_test_genotypes.c.o:/home/grg/src/tskit/c/build/../tests/testlib.h:40: first defined here
collect2: error: ld returned 1 exit status
[36/55] Linking target test_convert
FAILED: test_convert
cc  -o test_convert 'test_convert@exe/tests_test_convert.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group libtskit.a subprojects/kastore/libkastore.a libtestlib.a -lm /usr/lib/libcunit.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/:$ORIGIN/subprojects/kastore' -Wl,-rpath-link,/home/grg/src/tskit/c/build/ -Wl,-rpath-link,/home/grg/src/tskit/c/build/subprojects/kastore
/usr/bin/ld: libtestlib.a(tests_testlib.c.o):/home/grg/src/tskit/c/build/../tests/testlib.h:39: multiple definition of `_tmp_file_name'; test_convert@exe/tests_test_convert.c.o:/home/grg/src/tskit/c/build/../tests/testlib.h:39: first defined here
/usr/bin/ld: libtestlib.a(tests_testlib.c.o):/home/grg/src/tskit/c/build/../tests/testlib.h:40: multiple definition of `_devnull'; test_convert@exe/tests_test_convert.c.o:/home/grg/src/tskit/c/build/../tests/testlib.h:40: first defined here
collect2: error: ld returned 1 exit status
[41/55] Compiling C++ object 'cpp_sorting_example@exe/examples_cpp_sorting_example.cpp.o'
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by grahamgower**
Fixes #817.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM, thanks @grahamgower. We hit the same issue with msprime a few days ago. 

What's your compiler?

**Comment by grahamgower** [comment]
> What's your compiler?

Today, its gcc 10.1.0.

**Comment by jeromekelleher** [comment]
Ah, must be a change in gcc 10 then. Thanks.

**Comment by benjeffery** [comment]
Do we need to add gcc 10.X to the CI? Shouldn't be too hard.

**Comment by jeromekelleher** [comment]
:shrug: I'm not too bothered - we can't CI on every possible compiler, and stuff that breaks like this between gcc releases is going to be very rare.

**Comment by grahamgower** [comment]
I wouldn't worry too much about breakage, but GCC 10 does provide additional warnings that can be useful.

**Comment by grahamgower** [comment]
(and this particular PR fixes an issue arising in the linker, which is part of GNU binutils not GCC itself)

**Pull request merged**
