### PR TITLE
Require Python 3.6

### LINKED ISSUE #1171: Drop python 3.6
Numpy has now dropped support for python3.6, also msprime. We should consider doing so too. Opinions? 
@jeromekelleher, @petrelharp

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #1171

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Comment by benjeffery** [comment]
Hmm, getting an error that suggests that msprime and the LWT have been built on different versions of numpy. I've nuked the cache.

**Comment by hyanwong** [comment]
Hmm, any reason this hasn't merged yet @benjeffery ?

**Comment by benjeffery** [comment]
@mergifyio refresh

**Pull request merged**
