### PR TITLE
First pass at trim functions

### PR DESCRIPTION
**Pull request by hyanwong**
Closes https://github.com/tskit-dev/tskit/issues/288

No tests yet, as these will be easier once https://github.com/tskit-dev/tskit/pull/261 is committed, so that we can easily make tree sequences with no trees to left or right.

Also the documentation will need improving (e.g. document the TableCollection methods). I will do this once the general approach has been approved by @jeromekelleher .

### CODE REVIEW

**Comment by hyanwong** [comment]
Once https://github.com/tskit-dev/tskit/pull/261 is in, it would be rather easy to leave `slice` in as a convenience function. The documentation could simply say something like "`slice(start, stop): a convenient wrapper for `ts.keep_interval([(start, stop)]).trim()`.

But I'm equally happy not to have this.

**Comment by hyanwong** [comment]
The code in `remove_sites` duplicates code in the proposed `keep_intervals()` function in https://github.com/tskit-dev/tskit/pull/261. But I think we do need to remove sites in `trim`, as we don't know beforehand if the TS to trim has come from `keep_intervals` or not. If not, we might end up with negative positions for some sites.

I suspect the `remove_sites` functionality is more generally useful too. I've coded it up here as a tables function, so it should be possible (although maybe less efficient) to use it in `keep_intervals`, if we want to reduce code duplication.

**Comment by jeromekelleher** [comment]
This is quite a lot of code and will need a lot of testing. Can we push this back to after 0.2.0?

**Comment by hyanwong** [comment]
Yes - I'd much prefer to prioritise getting 0.2.0 out. I've only used the trim functionality (which was in `slice()`) in one bit of non-reusable code anyway, so it's probably just me requiring this at the moment.

**Comment by hyanwong** [comment]
Closing with the intent of opening a new PR, since the remove_sites functionality is now coded elsewhere

**Pull request closed without merging**
