### PR TITLE
Add missing changelog

### PR DESCRIPTION
**Pull request by benjeffery**
Apologies @brieuclehmann - none of the PRs had a changelog for your recent work. I've added it here and will also add to the github release page.

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/tskit-docs/PR-1048/)

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Review by brieuclehmann — APPROVED** [review]
LGTM, thanks!

**Comment by benjeffery** [comment]
@mergifyio rebase

**Pull request merged**
