### PR TITLE
Tidy up the evaluated python code

### LINKED ISSUE #1821: Make sure all python code chunks in markdown docs are executable
After #1802 there are still a few chunks of python code (e.g. in python-api.md) that are not formatted to be executed. We should also check that the ones that are executed make sense, as they might need `print()` statements inserting, or even splitting into separate code chunks.

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #1821

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Comment by jeromekelleher** [comment]
Is this ready to merge or do you have more changes @hyanwong?

**Comment by hyanwong** [comment]
No, you can merge. I just noticed some confusing wording and thought I might as well correct it, as well as add an example of setting a row, which is a new tskit 3.8/4.0 thing.

**Review by benjeffery — APPROVED** [review]
LGTM

**Pull request merged**
