### PR TITLE
Use msprime alpha on CI

### PR DESCRIPTION
**Pull request by benjeffery**
This works - although we get different SVGs, so we won't be able to get both versions of msprime to pass with the same expected SVG files.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
We could pull the alpha from conda-forge too, like we're doing in stdpopsim at the moment.

**Comment by jeromekelleher** [comment]
https://github.com/popsim-consortium/stdpopsim/blob/6e51b822aa6885a850fa68654746e1426e0eaccc/.github/workflows/tests.yml#L81

**Comment by benjeffery** [comment]
> We could pull the alpha from conda-forge too, like we're doing in stdpopsim at the moment.

As msprime 1.0 has wheels we don't actually need conda at all in the tskit CI anymore - is there any reason to keep it? We were only installing msprime with it and I don't think there is any meaningful testing that comes from using it.

**Comment by benjeffery** [comment]
I've added a commit to do that, seems to work!

**Comment by jeromekelleher** [comment]
That numpy ufunc failure thing looks nasty - any idea what's happening there?

**Comment by hyanwong** [comment]
I have a fix for one of the SVG errors, so that it passes on both new and old. Do you want it @benjeffery ? The other one is discussed in Slack and I think is unavoidable (I could try making an example TS a different way, though).

**Comment by hyanwong** [comment]
> I have a fix for one of the SVG errors, so that it passes on both new and old. Do you want it @benjeffery ? The other one is discussed in Slack and I think is unavoidable (I could try making an example TS a different way, though).

Actually there's a fix for both at https://github.com/tskit-dev/tskit/pull/1266/commits/9ec3ee0f0436fea6a19968ba24f3b8d60b4e2199

**Comment by benjeffery** [comment]
> That numpy ufunc failure thing looks nasty - any idea what's happening there?

Cache issue, fixed.

**Review by jeromekelleher — APPROVED** [review]

**Pull request merged**
