### PR TITLE
Static analysis docs

### PR DESCRIPTION
**Pull request by jeromekelleher**
Documenting how to run some static analysis tools for future selves.

It's not worth running this stuff in CI, I think - it takes quite a while and I don't want to have to get rid of all the false negatives that are there.

For the record, it seems the only warnings we're getting are about using strcat et al, which are all in places where the inputs are guaranteed to be well formed (we're only processing statically allocated strings internal to the library), and there's one warning about reordering the fields in a struct to optimise it. Here they are:

```
../tskit/genotypes.c:99:9: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
        strcpy(self->user_alleles_mem + offset, alleles[j]);
        ^
../tskit/genotypes.c:99:9: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
../tskit/tables.c:48:9: warning: Excessive padding in 'read_table_ragged_col_t' (8 padding bytes, where 0 is optimal). 
Optimal fields order: 
name, 
data_array_dest, 
data_len_dest, 
offset_array_dest, 
offset_array_mem, 
data_type, 
options, 
consider reordering the fields or adding explicit padding members [clang-analyzer-optin.performance.Padding]
typedef struct {
        ^
../tskit/tables.c:48:9: note: Excessive padding in 'read_table_ragged_col_t' (8 padding bytes, where 0 is optimal). Optimal fields order: name, data_array_dest, data_len_dest, offset_array_dest, offset_array_mem, data_type, options, consider reordering the fields or adding explicit padding members
../tskit/tables.c:206:9: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
        strcpy(offset_col_name, col->name);
        ^
../tskit/tables.c:206:9: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
../tskit/tables.c:207:9: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
        strcat(offset_col_name, "_offset");
        ^
../tskit/tables.c:207:9: note: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119
../tskit/tables.c:358:5: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
    strcpy(offset_col_name, col->name);
    ^
../tskit/tables.c:358:5: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
../tskit/tables.c:359:5: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
    strcat(offset_col_name, "_offset");
    ^
../tskit/tables.c:359:5: note: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119
Suppressed 2 warnings (2 in non-user code).
```

We could reorder the ``read_table_ragged_col_t`` struct, but it's totally not perf sensitive, and it would require changing a bunch of code which depends on this order for declaring these columns. We'd probably change over to using named initialisers if so, since the recommended ordering is less readable.

So, it's totally doable to get us fully clang-tidy clean, but I'm not particularly bothered about it. Happy to review PRs though if someone is motivated.

cc @molpopgen @bhaller

### CODE REVIEW

**Review by benjeffery — APPROVED** [review]
LGTM, nice to get fix the warnings, but agree it is low priority.

**Comment by bhaller** [comment]
Interesting.  Xcode doesn't show the ones you mention.  Perhaps there is a "threshold" setting, and you could set it a bit higher so you don't see this noise?  Personally, I don't run it often or in any automated way, but I do like to run it (and ASAN, and Valgrind, and so forth) before I do a release, to clean up any loose ends that have gone unnoticed.  It's a useful part of the toolbox, and does sometimes catch "real" bugs.  :->

**Comment by molpopgen** [comment]
> Xcode doesn't show the ones you mention.

This *could* be due to different clang tool chain versions.  `clang-tidy -h` doesn't give an obvious clue about a threshold setting.

I also agree this shouldn't be part of regular CI unless it is on some kind of infrequent schedule like running monthly on `main`.

**Comment by jeromekelleher** [comment]
Possibly Xcode has a different set of default "things to check" too, there's a long list of options you can enable.

**Pull request merged**
