### PR TITLE
Only push docs on main fork

### PR DESCRIPTION
**Pull request by benjeffery**
As raised at https://github.com/popsim-consortium/stdpopsim/issues/662

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/tskit-docs/947/)

**Review by grahamgower — APPROVED** [review]
LGTM!

I really wish github actions were off by default!

**Comment by benjeffery** [comment]
Yep, would be best. I'll try and get this stuff packaged up soon with closed PR removal etc.

**Review by jeromekelleher — APPROVED** [review]

**Comment by benjeffery** [comment]
@mergifyio rebase

**Pull request merged**
