### PR TITLE
Add tskit.json_schema

### LINKED ISSUE #1956: Easy way to make a metadata schema
I find it hard to remember what the specific way to make a simple schema is. We should have  function like ``tskit.json_schema`` or something that returns ``tskit.MetadataSchema({"codec": "json"})``. Or perhaps we want some sort of "SchemaBuilder" API that lets people build their schemas incrementally, adding properties? I don't think we need to support the full complexity of JSON schema, something simple that just supported adding a few (unnested) properties with documentation and a boolean required/not required flag would fit 99% of use cases. For anything more complex we can say "see the JSON schema spec".

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #1956

### CODE REVIEW

**Comment by jeromekelleher** [comment]
In #1944 I added MetadataSchema.permissive_json()`` as a class method that returned this instance - what do you think of that?

**Comment by benjeffery** [comment]
> In #1944 I added MetadataSchema.permissive_json()`` as a class method that returned this instance - what do you think of that?

Ah, hadn't gone closely through that PR yet - Seems a more organised place to put it.

**Comment by jeromekelleher** [comment]
Nice to get this documented for 0.4.0 @benjeffery?

**Comment by benjeffery** [comment]
@jeromekelleher Fixed up!

**Comment by benjeffery** [comment]
@jeromekelleher Fixed up!

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Pull request merged**
