### PR TITLE
Document properties in TableCollection, not ivars

### LINKED ISSUE #1975: Rationale for documenting TableCollection variables vs properties?
If you look at https://tskit.dev/tskit/docs/latest/python-api.html#tablecollection-and-table-classes you'll see that some things like `TableCollection.metadata` and `TableCollection.nbytes` are "properties" and others like `TableCollection.sequence_length` are variables, even though `sequence_length` is got and set by setters and getters. There doesn't seem to be any clear rationale for one vs the other. I suggest we might want to add a docstring to most of the `@property` decorated variables so that they are documented in the getter, and remove the `:ivar sequence_length: ` in the docstring of the class?

We could do that for the table getters such as `TableCollection.nodes`, `TableCollection.individuals`, etc too?

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #1975

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks good thanks. It would be nice to put some links in to the documentation explaining what "x" table is. Shall we open an issue to track?

**Review by jeromekelleher — APPROVED** [review]

**Comment by hyanwong** [comment]
> Looks good thanks. It would be nice to put some links in to the documentation explaining what "x" table is. Shall we open an issue to track?

You mean a link in the property docstrings? Or something in the python-api.md file, e.g.

```
#### General properties

Specific {ref}`tables<sec_tables_api_table>` in the {class}`TableCollection` can be
accessed using the plural version of their name, so that, for instance, the
individual table can be accessed using `table_collection.individuals`.

```{eval-rst}
Table access
    .. autosummary::
      TableCollection.individuals
      TableCollection.nodes
      TableCollection.edges
      TableCollection.migrations
      TableCollection.sites
      TableCollection.mutations
      TableCollection.populations
      TableCollection.provenances

Other properties
    .. autosummary::
      TableCollection.file_uuid
      TableCollection.indexes
      TableCollection.nbytes
      TableCollection.name_map
      TableCollection.metadata
      TableCollection.metadata_bytes
      TableCollection.metadata_schema
      TableCollection.sequence_length
      TableCollection.time_units
```

**Comment by jeromekelleher** [comment]
> You mean a link in the property docstrings? 

I meant just a link in the property docstring; they're quite terse and unhelpful at the moment. Terse is fine if there's some documentation at the end of a link though.

Your summary looks good too though, please add it in if you think it helps.

**Comment by hyanwong** [comment]
> I meant just a link in the property docstring; they're quite terse and unhelpful at the moment. Terse is fine if there's some documentation at the end of a link though.

We could literally just add a link:

```
    def individuals(self) -> IndividualTable:
        """
        The :ref:`sec-individual-table-definition`
        """
        return IndividualTable(ll_table=self._ll_tables.individuals)
```


> Your summary looks good too though, please add it in if you think it helps.

Will do.

**Comment by hyanwong** [comment]
Both added. Ready to merge.

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Pull request merged**
