### PR TITLE
Add example of TSK_TAKE_OWNERSHIP semantics

### PR DESCRIPTION
**Pull request by molpopgen**
## Description

Thanks for contributing to tskit! :heart:
A guide to the PR process is [here](https://tskit.readthedocs.io/en/latest/development.html#development_workflow_git)

Adds a C example of how to correctly use TSK_TAKE_OWNERSHIP.

# PR Checklist:

- [ ] Tests that fully cover new/changed functionality.
- [ ] Documentation including tutorial content if appropriate.
- [ ] Changelogs, if there are API changes.

### CODE REVIEW

**Review by benjeffery — APPROVED** [review]
Thanks @molpopgen!

**Comment by molpopgen** [comment]
Shall we merge?

**Comment by benjeffery** [comment]
@molpopgen We merge using the "AUTOMERGE REQUESTED" label - it rebases and does CI. No biggie though.

**Comment by molpopgen** [comment]
This is why I shouln't have permissions for things! ;)

**Pull request merged**
