### PR TITLE
Backwards algorithm (haploid) tree implementation and testing

### PR DESCRIPTION
**Pull request by astheeggeggs**
Added tree-based implementation of the backwards algorithm for haploid data, and include a series of tests using lshmm for testing (very similar to the diploid implementation and testing).

### CODE REVIEW

**Comment by astheeggeggs** [comment]
TODO: allow for multiple mutations at each site (currently all testing assumes infinite sites model)

**Comment by jeromekelleher** [comment]
I'm not a big fan of these large chunks of duplicated code and splitting into files like ``_viterbi`` and ``_fb`` @astheeggeggs -  is there any way we could merge this into the existing ``test_haplotype_matching.py`` file? We should have only one copy of this ``LsHmm`` class, or else it doesn't really help with writing the low-level code.

**Comment by astheeggeggs** [comment]
merged fb and viterbi testing for haploid

**Comment by benjeffery** [comment]
@astheeggeggs We had a restriction on `lshmm` for Python3.11 as numba wasn't updated to 3.11. It is now so I've removed the restriction and then the tests should pass.

**Comment by astheeggeggs** [comment]
Huzzah! Thanks Ben!

**Review by jeromekelleher — APPROVED** [review]
Awesome, let's merge!

**Comment by jeromekelleher** [comment]
@benjeffery would you mind squashing this down a bit since you already have it checked out please?

**Comment by benjeffery** [comment]
> @benjeffery would you mind squashing this down a bit since you already have it checked out please?

Done

**Comment by jeromekelleher** [comment]
Whoops somethings going weird here - did you mean to update this branch @astheeggeggs?

**Comment by astheeggeggs** [comment]
Whoops - I'm not sure what I've done here

**Comment by benjeffery** [comment]
Done!

**Comment by jeromekelleher** [comment]
@mergifyio rebase

**Pull request merged**
