### PR TITLE
Check that individuals have the same pop, time, & contiguous nodes

### LINKED ISSUE #749: Valid TS should not allow nodes from multiple populations within the same individual
At the moment, it appears as if it is valid to create nodes within the same individual that belong to different populations (code below). I think we should ban this, and raise an error when tables with this property are turned into a tree sequence. Does this seem sensible? I don't think that having a single individual containing two sample nodes each belong to a different population makes much sense.

```
ts = msprime.simulate(4, random_seed=1)
tables = ts.tables
tables.individuals.add_row()
tables.individuals.add_row()
ind = tables.nodes.individual
pop = tables.nodes.population
ind[ts.samples()] = np.arange(ts.num_samples)//2
tables.nodes.individual = ind
pop = np.full(ts.num_nodes, tskit.NULL, dtype=tables.nodes.population.dtype)
pop[0] = 0  # only sample 0 has a population, but 
tables.nodes.population = pop
new_ts = tables.tree_sequence()
print(str(new_ts.tables.nodes))

id	flags	population	individual	time	metadata
0	1	0	0	0.00000000000000	
1	1	-1	0	0.00000000000000	
2	1	-1	1	0.00000000000000	
3	1	-1	1	0.00000000000000	
4	0	-1	-1	0.17986860883729	
5	0	-1	-1	1.97752050080185	
6	0	-1	-1	2.69754599651364	

```

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #749 and #750

### CODE REVIEW

**Comment by hyanwong** [comment]
NB: I had to remove 2 tests which assumed it was reasonable to allow interleaved individuals.

**Comment by jeromekelleher** [comment]
If it's OK to have interleaved individuals now, then I don't see any reason to make this requirement stricter. We should just remove the out-of-date note from the docs.

**Comment by petrelharp** [comment]
> We should just remove the out-of-date note from the docs.

I'm OK with that also, although I feel like we'll be making our lives in the future easier if we do enforce this requirement. But possibly breaking people's code is bad, soo...

**Comment by hyanwong** [comment]
I'm ambivalent here, but I think it would be good to sort out this inconsistency (and #750) before v0.3.0 if possible.

**Comment by hyanwong** [comment]
Closing to re-work

**Pull request closed without merging**
