### PR TITLE
tskit CLI

### PR DESCRIPTION
**Pull request by jeromekelleher**
Porting and improving the msprime msp CLI.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This adds two commands I've been missing to the CLI, ``info`` and ``trees``
```
$ python3 -m tskit info tmp.trees
sequence_length:  1.0
trees:            2
samples:          5
individuals:      0
nodes:            10
edges:            12
sites:            9
mutations:        9
migrations:       0
populations:      1
provenances:      1
```
and
```
$ python3 -m tskit trees tmp.trees  -d
tree 0:
  num_sites: 5
  interval:  (0.000000, 0.601622)
    9
 ┏━━┻━┓
 ┃    8
 ┃  ┏━┻┓
 7  ┃  ┃
┏┻┓ ┃  ┃
┃ ┃ ┃  6
┃ ┃ ┃ ┏┻┓
1 2 0 3 4

tree 1:
  num_sites: 4
  interval:  (0.601622, 1.000000)
     9
  ┏━━┻━━┓
  8     ┃
┏━┻━┓   ┃
┃   6   ┃
┃ ┏━┻┓  ┃
┃ ┃  5  ┃
┃ ┃ ┏┻┓ ┃
0 4 1 3 2

```

The output is pretty rough. Any ideas on how to improve it anyone?

**Comment by petrelharp** [comment]
Looks totally great to me. Although there should be some way to limit the number of trees that get spit out if they are very numerous.

**Comment by jeromekelleher** [comment]
> Looks totally great to me. Although there should be some way to limit the number of trees that get spit out if they are very numerous.

Great, thanks @petrelharp! I guess the best way to do this is to have  ``--start`` and ``--stop`` arguments for ``tskit trees``, which we can do one #24 is implemented. In the mean time, I'd imagine the most practical use of this is to pipe it into less, so it's not such a big deal if there are gazillions of trees, I think.

**Comment by jeromekelleher** [comment]
OK, going to merge this much. We can improve the output as we go.

**Pull request merged**
