### PR TITLE
Added methods to sort and squash segments in the IbdFinder output.

### LINKED ISSUE #2459: Provide option to squash IBD output?
One of the most important comments I got in my thesis examination was regarding our definition of IBD. Our current implementation of `ibd_segments` treats segments as distinct if they have been inherited along distinct 'genealogical paths', which are essentially sequences of edges. So in this instance, 
```
    #
    #        4       |      4       |        4
    #       / \      |     / \      |       / \
    #      /   \     |    /   3     |      /   \
    #     /     \    |   2     \    |     /     \
    #    /       \   |  /       \   |    /       \
    #   0         1  | 0         1  |   0         1
    #                |              |
    #                0.2            0.7
```
there will be 3 separate IBD segments for the sample pair (0,1), because the paths in the middle tree explicitly contain some extra intermediary nodes. (This has caused confusion for other users before: see #1479).

I was pretty sure this behaviour was desirable until I read this comment of Graham's:

> if I’m understanding things correctly, I’m not sure the path definition actually lines up with most people’s definition of halotype IBD. The good news is that given segments called from the tree-sequence path definition you can always stitch them to form IBD segments in post-processing, but I caution against calling the original segments IBD. (*Indeed, there are many unsampled lineages in the population that will coalesce and recombine with the lineages [0] & [1] before [0] & [1] coalesce together, our definition of IBD should depend on the properties of just the history of the pair not of the coalescence pattern of other sampled or unsampled alleles.

This is a super valid point, and kind of major imo. In many of the tree sequences we come across, nodes like (2) and (3) will be coalescence nodes that relate our samples to some other sample that has recombined at the breakpoints (who we are perhaps uninterested in). It's bad if our definition of IBD between the pair (0, 1) depends on whether those other samples are included in the trees or not, and currently it does.

> The good news is that given segments called from the tree-sequence path definition you can always stitch them to form IBD segments in post-processing

We've certainly talked about doing this before, but I'm unsure of how much effort it will take. I'm about to push up a draft PR that implements these changes in our Python `IbdFinder`, but I'm not sure this would translate well to the C code given the fancy struct that Jerome made for the output. The necessary algorithms are themselves fairly simple -- a sort method and a squash method, both very similar to those used on edge tables.

pinging @jeromekelleher, @petrelharp

### PR DESCRIPTION
**Pull request by gtsambos**
Fixes #2459 -- see the issue for discussion about why this is needed. Draft only at the moment.

### PR Checklist:

- [ ] Tests that fully cover new/changed functionality.
- [ ] Documentation including tutorial content if appropriate.
- [ ] Changelogs, if there are API changes.

### CODE REVIEW

**Comment by gtsambos** [comment]
Hey @hyanwong! Unfortunately, we both made some pretty involved changes to the test_highlevel.py file in the past few days. I think I've fixed up the merge conflict, but I can't figure out how to get my tests to run with the argument that I added into `get_example_tree_sequences()`. Currently I'm just skipping these tests because I don't fully understand the syntax of your additions -- do you know how to ensure these tests 'see' the argument I've added in?

**Comment by hyanwong** [comment]
It was @benjeffery who fixed up `get_example_tree_sequences()` to run in parallel, cached, so that `parameterize` worked properly. He might be able to suggest a fix?

**Comment by benjeffery** [comment]
I'll take a look now

**Comment by benjeffery** [comment]
I think the simplest thing here is to remove `custom_max`.
I've done this in https://github.com/tskit-dev/tskit/commit/a3aa3da8f2ba991a48967011a230a32cf6fe62cd
Currently, I've set the `N` numbers to those generated when `custom_max` was `15`. Once all the IBD tests pass we should add in some even numbers again and skip them in the IBD tests? (I'm assuming that you need them to be odd, as all those generated by `custom_max` were?

**Comment by gtsambos** [comment]
Thanks @benjeffery and sorry for the late reply -- I had to take a few days off to deal with some urgent moving-to-the-US things.

> Currently, I've set the N numbers to those generated when custom_max was 15. Once all the IBD tests pass we should add in some even numbers again and skip them in the IBD tests? (I'm assuming that you need them to be odd, as all those generated by custom_max were?

I added this argument because some of my changes in this PR make IbdFinder run much more slowly, to the point where they look like they're hanging. (This is likely a Python-specific problem -- as we discuss in #2459, the C code works differently because it uses an AVL tree to do the sorting). But I didn't want to omit the tests entirely, as they cover some useful edge cases, so I wanted to run them with smaller sample sizes than the ones hard-coded in.

**Comment by benjeffery** [comment]
> I added this argument because some of my changes in this PR make IbdFinder run much more slowly, to the point where they look like they're hanging. (This is likely a Python-specific problem -- as we discuss in #2459, the C code works differently because it uses an AVL tree to do the sorting). But I didn't want to omit the tests entirely, as they cover some useful edge cases, so I wanted to run them with smaller sample sizes than the ones hard-coded in.

We can leave the slow examples in the examples - but skip them in these tests?

**Comment by benjeffery** [comment]
I've rebased this to main - the tests here only add a few seconds on my machine. @jeromekelleher I think this is pretty complete if you want to have a quick look to check?

**Review by benjeffery — APPROVED** [review]

**Comment by benjeffery** [comment]
@mergifyio update

**Pull request merged**
