### PR TITLE
Document rf_distance()

### PR DESCRIPTION
**Pull request by hyanwong**
In the first commit in the PR, I have moved all the `kc_distance` testing from `test_topology.py` into the new `test_distance_metrics.py` file, created by @Billyzhang1229 for the rf tests. This seems more logical, and usefully slims down the huge `test_topology.py` file. At some point we might want to rationalise that file though, as the `kc_` testing and the `rf_` testing take rather different approaches.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
Great, thanks @hyanwong

**Comment by benjeffery** [comment]
I assume this covers #2992? Thanks @hyanwong that was the last issue for 0.6.0!

**Comment by hyanwong** [comment]
Changelog added. Let's get this baby shipped @benjeffery !

**Comment by benjeffery** [comment]
@mergifyio rebase

**Pull request merged**
