### PR TITLE
Add "ago"

### LINKED ISSUE #2977: Trivial wording change
I think in the SVG outputs, for clarity the Y axis should say `f"Time ago ({time units})"` rather than `f"Time ({time units})"`. Does that seem reasonable? If so I'll make the change.

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #2977

I made this trivial change on a branch but forgot to PR it!

### CODE REVIEW

**Comment by hyanwong** [comment]
@mergifyio rebase

**Comment by benjeffery** [comment]
@Mergifyio rebase

**Review by benjeffery — APPROVED** [review]

**Comment by benjeffery** [comment]
@Mergifyio rebase

**Comment by benjeffery** [comment]
@Mergifyio rebase

**Pull request merged**
