### PR TITLE
Improve stat docs

### PR DESCRIPTION
**Pull request by petrelharp**
This is for discussion and iteration on the docs. I've fixed the links as pointed out by @molpopgen and as suggested on email:

> a Python example showing exactly what 'f' must do would be really useful.  Likewise, for sample_count_stat.  The docs state that f returns a 1d array, but it isn't clear (to me) if that array is of length 1 in the case of 1 sample set, but it seems like it must be, else it would have to be  higher dimension for > 1 sample set?

I made an example for sample counts; I was having a hard time coming up with a not-super-wierd example for general_stat; any suggestions?

### CODE REVIEW

**Comment by molpopgen** [comment]
Once I get a chance to play around a bit, maybe I'll come up with a "general" stat example.

**Comment by petrelharp** [comment]
I thought about things like "sum of phenotype in subset of samples" or "produce of mean latitude and mean longitude of samples having this allele"...

**Comment by molpopgen** [comment]
> I thought about things like "sum of phenotype in subset of samples" or "produce of mean latitude and mean longitude of samples having this allele"...

The z-score due to genotypes with this allele could be cool?

**Comment by molpopgen** [comment]
> The z-score due to genotypes with this allele could be cool?

nevermind--this is complex b/c you'd have to know individuals?

**Comment by petrelharp** [comment]
> The z-score due to genotypes with this allele could be cool?

what is that?

**Comment by molpopgen** [comment]
> what is that?

(Mean phenotype of everyone with the mutation - population mean phenotype)/(std dev of phenotype in population).  

"Population" could mean "sample" here, too.

**Comment by petrelharp** [comment]
That's [this])https://tskit.readthedocs.io/en/latest/python-api.html#tskit.TreeSequence.trait_correlation) (which I see we forgot to link to in the stats docs...)

**Comment by petrelharp** [comment]
Made that link.

**Comment by jeromekelleher** [comment]
Shall we merge this much @petrelharp? If so, can you rebase and merge it please?

**Pull request merged**
