### PR TITLE
Sackin C implementation

### PR DESCRIPTION
**Pull request by jeromekelleher**
Also includes the C testing framework for the rest of the balance metrics. So, to implement other balance metrics in C we add the implementation, and then test the returned value in these three test function.

cc @jeremyguez

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Sigh - codecov has gone a bit haywire again. I think everything that can be covered is covered.

**Comment by jeromekelleher** [comment]
Bumping this one @benjeffery

**Review by benjeffery — APPROVED** [review]
LGTM - One question, is a 32bit `depth` only safe when `_TSK_BIG_TABLES` is not used? I'm not sure how paranoid to be here, but maybe the type of `depth` should be conditional on that macro?

**Comment by jeromekelleher** [comment]
> LGTM - One question, is a 32bit depth only safe when _TSK_BIG_TABLES is not used? I'm not sure how paranoid to be here, but maybe the type of depth should be conditional on that macro?

Hah, good spot. I changed the depth value to a ``tsk_id_t`` as that is always safe.

**Pull request merged**
