### PR TITLE
Minor docs fix for sample_count_stat().

### PR DESCRIPTION
**Pull request by grahamgower**
## Description

Just a few characters missing from the code in the docstring.

# PR Checklist:

- [ N/A] Tests that fully cover new/changed functionality.
- [ N/A] Documentation including tutorial content if appropriate.
- [ N/A] Changelogs, if there are API changes.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM, thanks @grahamgower!

**Comment by benjeffery** [comment]
We have a lint issue, I'll fix and force push.

**Comment by benjeffery** [comment]
Black wanted a line longer than flake8 as black doesn't count the margin and flake8 does! Disabled that error code for the line. WIll merge now.

**Comment by grahamgower** [comment]
Thanks for taking care of the black/flake8 conflict @benjeffery!

**Pull request merged**
