### PR TITLE
Add readme badges

### LINKED ISSUE #469: GitHub landing pages for Python and C
The current GitHub readme contains generic information about the tskit project. It would be nice if we also had specific landing pages for the C and Python libraries (i.e., README.md files), with links to these from the top-level README.

These should include any relevant badges (i.e, Black format, download counts, CI badges etc for Python; I guess just the Circle CI badge for C).

### PR DESCRIPTION
**Pull request by benjeffery**
Closes #469
Apparently appveyor needs a key from their settings page, so have skipped it for now.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Might be nice to split some of these out into the Python subdirectory, as this is the root of the Python package. Stuff like downloads all refers to the Python package.

**Comment by jeromekelleher** [comment]
Is it a good idea to split these badges up between the C and Python directories (with links in the top-level README to these READMEs, I guess), or should we put it all into different sections of the top level README do you think @benjeffery?

I can imagine having badges that only apply to the C code in there at some point too, say things like coverity scan.

**Comment by benjeffery** [comment]
@jeromekelleher I've updated this - I think it might be enough to close #469. Most people will land on the github front page first so I think putting both C and python there is better than having to click through.

**Comment by jeromekelleher** [comment]
Yes, good call, thanks.

**Pull request merged**
