### PR TITLE
Stat function interface

### PR DESCRIPTION
**Pull request by molpopgen**
Fix for #280

### CODE REVIEW

**Comment by petrelharp** [comment]
Looks good, thanks!  Some nitpicking: there is one remaining `print` and I'd also vote for removing all the lines that say `# Hack`: I think we won't know what that means in two months and it will make our future selves nervous.

**Comment by molpopgen** [comment]
>  it will make our future selves nervous

Not an accident :)

**Comment by jeromekelleher** [comment]
LGTM, thanks @molpopgen. Ready to merge after a squash.

**Comment by molpopgen** [comment]
I don't have merge permissions.

**Comment by jeromekelleher** [comment]
Can you squash the commits down to one (like described [here](https://stdpopsim.readthedocs.io/en/latest/development.html#github-workflow)) please?

**Comment by molpopgen** [comment]
Ok.  I just figured someone with right access would squash from the web
interface.

**Comment by jeromekelleher** [comment]
> Ok. I just figured someone with right access would squash from the web interface.

It's a different squash  - the commits just drop in flat into the history with no edits to the commit messages or anything, and you don't see the merge commit (which is handy for tracking PRs when writing release notes).

**Comment by jeromekelleher** [comment]
Merged - thanks @molpopgen!

**Pull request merged**
