### PR TITLE
More clarification for variant.num_alleles docs

### PR DESCRIPTION
**Pull request by hyanwong**

### CODE REVIEW

**Comment by benjeffery** [comment]
I'm trying to fix CI here, I think the recent pip changes are problematic.

**Comment by jeromekelleher** [comment]
Something to do with setuptools? Should we open an issue to track?

**Comment by benjeffery** [comment]
> Something to do with setuptools? Should we open an issue to track?

Fixed in #2474

**Comment by hyanwong** [comment]
@mergifyio rebase

**Pull request merged**
