### PR TITLE
Fix out-of-bounds error on 32bit.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Fixes segfault on 32 bit machines

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/tskit-docs/1002/)

**Comment by jeromekelleher** [comment]
Looks like a problem with the lint workflow @benjeffery?
```

Run echo "::set-env name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
Error: Unable to process command '::set-env name=PY::d874f77ec1348dfde58a9317309117a9df04cdc975815e70e2910a54b56d97ae' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by benjeffery** [comment]
Yep, also for msprime https://github.com/tskit-dev/msprime/pull/1252#issuecomment-728437519 will fix next.

**Comment by benjeffery** [comment]
@mergifyio rebase

**Review by benjeffery — APPROVED** [review]
LGTM!

**Pull request merged**
