### PR TITLE
Use `takeset` to make loading zero-copy

### LINKED ISSUE #2131: Use column takeset and kastore GET_TAKES_OWNSHIP for zero-copy loading
Should be a case of setting the appropriate flags to kastore_open and using takeset when reading the individual table columns.

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #2131 

Here is a comparison of this main and this branch's memory use (main first):
main
branch

Almost all of the remaining overhead is due to casting offsets up to 64bit, which uses 3x their size, with that off we get:
branch_nocast

### CODE REVIEW

**Comment by petrelharp** [comment]
Awesome to see this moving. What's memtestmsp.py doing?

**Comment by benjeffery** [comment]
All the tests finally pass here. Some feedback on how I've solved the edge cases (e.g. `if` after `out:`) would be good.

**Comment by jeromekelleher** [comment]
Let's get #2032 squared away first, will make it easier to see the new stuff here. I think we're pretty sold on the takeset idea basically working anyway, right?

**Comment by benjeffery** [comment]
Here's a clean example that we're getting what we expect in a very simple case - this is a tree sequence with only one row in the populations table: `tc.populations.add_row(metadata=b"a"*10_000_000_000)` and the memory usage when we load it to a `TableCollection`:
main_big_ragged
main_big_ragged

**Comment by jeromekelleher** [comment]
Brilliant! So all working as expected now then?

**Comment by benjeffery** [comment]
> So all working as expected now then? 

Yes, I believe so! It has been useful to break all this down and check we understand it all. Basically,  the 0.05seconds after 0.2 are snipped out and don't happen, so as well as the memory usage falling the load is quicker!

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by benjeffery** [comment]
Now that I've got a clean diff I can see a couple of errors, will fix today so don't review yet!

**Comment by benjeffery** [comment]
@jeromekelleher Ok! Ready for review.

**Comment by benjeffery** [comment]
@jeromekelleher I've made the changes we discussed - in doing so it revealed that `read_table_ragged_col_t` had two references to the offset array, one of which was direct and therefore non-NULLable by the caller of `read_tables`. I couldn't see why this was needed so have removed the second reference, it was added when we added support for 64bit.

**Review by jeromekelleher — APPROVED** [review]
Looks great, let's merge!

**Pull request merged**
