### PR TITLE
Add `_repr_html_` to tables

### LINKED ISSUE #512: Jupyter notebook friendly output for tables
Add ``_repr_html_`` for tables to display them nicely in Jupyter notebooks.

### PR DESCRIPTION
**Pull request by benjeffery**
Closes #512 

This method is called by jupyter notebooks to display nice-looking tables. Here's a screenshot:
Screenshot from 2020-04-07 01-01-32

### CODE REVIEW

**Comment by benjeffery** [comment]
No idea why the docs are broken, they build locally. Will fix the CI tomorrow, but def not the fault of these changes.

**Comment by jeromekelleher** [comment]
Very tidy, I like it!

**Comment by jeromekelleher** [comment]
One to add to the CHANGELOG too.

**Comment by benjeffery** [comment]
@jeromekelleher changelog added (fixed up a few other entries too)

**Comment by jeromekelleher** [comment]
Looks like the docs build is failing because of a new sphinx version. Sigh.

**Comment by benjeffery** [comment]
Things like this are why deps should be version-pinned, at least for the CI. At the moment the CI isn't deterministic. We can use https://dependabot.com/ to keep the pinned versions up-to-date. It submits PRs automatically and we would see the CI break there instead of here.

**Comment by benjeffery** [comment]
@jeromekelleher I'm fixing the docs - will be in a diff PR.

**Pull request merged**
