### PR TITLE
Add installation details

### PR DESCRIPTION
**Pull request by hyanwong**
As per https://github.com/tskit-dev/tskit/issues/127#issuecomment-466639790

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This belongs in the documentation, not the README (no point in splitting documentation over multiple locations). Can you move it into the installation page (docs/installation.rst) please?

**Comment by hyanwong** [comment]
Sure, didn't spot that.

**Comment by jeromekelleher** [comment]
Probably no harm adding a link in the README to the installation docs all right though, e.g., https://github.com/tskit-dev/msprime

**Comment by jeromekelleher** [comment]
Looks good, thanks. Would you mind rebasing and squashing please? (Keeping a clean history helps, and there's no need for more than one commit for this.)

**Comment by hyanwong** [comment]
Will do. I was thinking it would be good to have a summary in the README, along the lines of the following. I could add that before squashing.

Succinct tree sequences are a highly efficient way of storing a set of related DNA sequences by storing their ancestral history as a set of correlated trees along the genome. The tree sequence format is output by a number of software libraries and programs (such as [msprime](), [SLiM](), [fwdpp](), and [tsinfer]()) that either simulate or infer the evolutionary history of genetic sequences.

The `tskit` library provides the underlying functionality used to load, examine, and manipulate tree sequences. It often forms part of an installation of other software packages such as those listed above. Please see the [documentation](https://tskit.readthedocs.io/en/latest/) for further details, including [installation instructions](https://tskit.readthedocs.io/en/latest/installation.html).

**Comment by jeromekelleher** [comment]
Nice! Sure, go for it.

**Pull request closed without merging**
