### PR TITLE
Mention genetic statistics in the main README & intro

### PR DESCRIPTION
**Pull request by hyanwong**
I think many people will come into tskit (rather than, say, msprime) because of @petrelharp 's lovely efficient stats calculations, so we should mention them in the initial readme and the intro section in the docs. This is my attempt to do that.

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/tskit-docs/926/)

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Comment by jeromekelleher** [comment]
@mergifyIO rebase

**Comment by petrelharp** [comment]
aw gee, you're too nice.

**Pull request merged**
