### PR TITLE
Switch codecov to bash uploading

### PR DESCRIPTION
**Pull request by benjeffery**
We've been getting very flakey codecov uploads, one suggestion was to switch to the bash uploader. Trying this out here.

### CODE REVIEW

**Comment by benjeffery** [comment]
@jeromekelleher This seems more reliable - have triggered it 4 times and it hasn't failed. However, I can't tell why, but it seems to be measuring coverage slightly differently - in particular partial branches.

**Review by jeromekelleher — APPROVED** [review]
worth a try!

**Comment by jeromekelleher** [comment]
Crap, just hit the wrong button there. Hope it doesn't muck things up too much.

**Comment by benjeffery** [comment]
No harm done, just broke our streak of no overlapping paths on the network diagram!

**Comment by jeromekelleher** [comment]
:cry:

**Comment by jeromekelleher** [comment]
I was proud of that linear streak!

**Pull request merged**
