### PR TITLE
Readme & install

### PR DESCRIPTION
**Pull request by hyanwong**
Update installation.rst, add link to installation instructions, add to README

### CODE REVIEW

**Comment by hyanwong** [comment]
Just testing here - I can't figure out an easy way to squash, but according to https://help.github.com/en/articles/merging-a-pull-request you can just select "Squash and merge" in GitHub when accepting the merge. Would that be easier?

**Comment by jeromekelleher** [comment]
See point 5 [here](https://stdpopsim.readthedocs.io/en/latest/development.html#github-workflow).

**Comment by jeromekelleher** [comment]
This [guide](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) explains squashing.

**Comment by hyanwong** [comment]
> This [guide](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) explains squashing.

Weirdly I though I had done this. Will re-try

**Comment by jeromekelleher** [comment]
> Weirdly I though I had done this. Will re-try

I can take you through it later. Rebasing is an essential git-skill, well worth the initial effort figuring it out.

**Comment by hyanwong** [comment]
Thanks. I did try rebasing in 509c220, but somehow it left the history in there.

**Comment by jeromekelleher** [comment]
```
$ git fetch upstream
$ git rebase -i upstream/master
```
and 'squash' everything except first commit. There's no conflicts, so it has to work. What are you doing?

**Comment by hyanwong** [comment]
I think I probably didn't rebase based on upstream/master

**Pull request merged**
