### PR TITLE
Fix collision of VERSION files with Clang++ <version> header files

### LINKED ISSUE #2133: VERSION files in tskit/kastore c folders lead to CPP compilation failure on macOS
When I used meson/ninjia/x86_64-apple-darwin13.4.0-clang++(in a Conda environment) to compile the sources files under `tskit/c`, I got many line of errors. 

One type of them are due to the failure to find system include paths. So I added the paths to meson.build for cpp files.  And it worked.
```
cpp_sys_dep = declare_dependency(include_directories: [
    '/Users/xxxx/mambaforge/envs/cxx/bin/../include/c++/v1',
    '/Users/xxx/mambaforge/envs/cxx/lib/clang/12.0.1/include',
    '/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include',
    '/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks'
])

executable('cpp_sorting_example',
          sources: ['examples/cpp_sorting_example.cpp'], 
          link_with: [tskit_lib], dependencies: [cpp_sys_dep,lib_deps])
```

The second type of errors are like this:
```
../version:1:1: error: expected unqualified-id
0.99.15
```

If I change file content to `extern int xxxx;`, it will compile.

Many of Apple clang++'s standard headers include a internal header file named `version` (without an extension name).   I think the Apple clang++ mistakenly use the tskit/c VERSION file as its own header file (`version`).

It seems that this is can be fixed by simply adding the `.txt` extension name to the `tskit/c/VERSION` and `subprojects/kastore/VERSION` files and update the 2nd line of `meson.build` to `  version: files('VERSION.txt')`.

Have you seen this before? Am I missing something from meson part (like a meson way of setting the `-isystem`)?

### PR DESCRIPTION
**Pull request by gbinux**
## Description

Many of Apple clang++'s standard headers include a internal header file named version (without an extension name). With the `VERSION` files in the `c` folder, Apple clang++ mistakenly uses the VERSION file as its own header file `<version>`. This causes problems when compiling the cpp test codes on macOS.

It seems this is can be fixed by simply adding the `.txt` extension name to the `tskit/c/VERSION` and `subprojects/kastore/VERSION` files and update the 2nd line of`meson.build` to `version: files('VERSION.txt')`.

Fixes #2133 

# PR Checklist:

- [ ] Tests that fully cover new/changed functionality.
- [ ] Documentation including tutorial content if appropriate.
- [ ] Changelogs, if there are API changes.

### CODE REVIEW

**Review by jeromekelleher — COMMENTED** [review]
This looks great, thanks @gbinux! Unfortunately we need to work on kastore separately, release, and then pull in the changes. (https://github.com/tskit-dev/kastore/issues/186)

(I thought I reviewed this already, apologies for any repetition)

**Comment by gbinux** [comment]
Sorry. I have not seen this inter-connected case before.  Do you want me to do one PR on kastore (VERSION and meson.build file) and the other on tskit (tskit's VERSION and meson.build file but no changes in subproject folders)? @jeromekelleher

**Comment by benjeffery** [comment]
@jeromekelleher Rebased and fixed up.

**Comment by jeromekelleher** [comment]
Looks like Python tests need fixing up

**Comment by benjeffery** [comment]
Missed one! Fixed.

**Comment by gbinux** [comment]
Sorry, I think there is one more minor thing in the meson build file if I understand it correctly.  It is unrelated to this VERSION file name issue but it is a small one that could be easily fixed at the same time?

https://github.com/tskit-dev/tskit/blob/d0369d4c6e5058e3d19df0fc2847659a3b514ed1/c/meson.build#L36-L38
The shared library is defined but not referred. (Only relevant when it is not included as a subproject)

**Comment by jeromekelleher** [comment]
Can we follow that one up in another issue please @gbinux? Include your error messages as well please.

**Comment by gbinux** [comment]
> Can we follow that one up in another issue please @gbinux? Include your error messages as well please.

Sure

**Review by benjeffery — APPROVED** [review]

**Comment by benjeffery** [comment]
Merging this one, thanks @gbinux!

**Pull request merged**
