### PR TITLE
Fix dependancy versions

### PR DESCRIPTION
**Pull request by benjeffery**
I've gone through our deps as a result of https://github.com/tskit-dev/msprime/issues/1157 and all of them need a minimum version for things to work.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM. Are any of these super-recent? We might want to roll back on whatever we're using it for if so.

**Comment by benjeffery** [comment]
> Are any of these super-recent

Nah, almost all by a couple of years at least.

**Comment by castedo** [comment]
As far as I can tell, I confirm those two new min version requirements that Ben added are not super-recent.
Fedora 31 (penultimate stable release) installs rpm packages of:
python3-svgwrite-1.4-1.fc31.noarch
python3-h5py-2.9.0-5.fc31.x86_64
which are notable newer than the min req Ben put in.

**Review by castedo — COMMENTED** [review]
I don't really know what I'm doing here. :) Let's see if this is approving a review request ... my first!

**Comment by benjeffery** [comment]
Thanks @castedo, great to confirm that.

**Pull request merged**
