### PR TITLE
clarification to simplify documentation

### PR DESCRIPTION
**Pull request by petrelharp**
Gee, making a qiuck doc fix on the web interface *is* pretty easy.  I just clicked the little pencil up top of the file and *boom*.  cc @hyanwong

### CODE REVIEW

**Comment by hyanwong** [comment]
Do you know if it works if you don't already have a fork, @petrelharp ? I would hope drive-by doc correction could be made by novices / non-github users.

**Comment by petrelharp** [comment]
No forking involved! You do have to be signed in to github. I guess I don't know if this works for non-owners? Here's what it looks like for me:
Screenshot from 2020-04-27 11-38-45
Screenshot from 2020-04-27 11-40-08
Screenshot from 2020-04-27 11-40-33

**Comment by petrelharp** [comment]
How's the change look, btw? Shall I merge it?

**Comment by hyanwong** [comment]
> How's the change look, btw? Shall I merge it?

I think you mean "in the old (unsimplified) tree sequence," don't you? Otherwise this is clearer, yes.

p.s. I think you get that nice edit because you have write access to the repo. I get a "we will make this change in your fork of the repo, and make it into a PR from there". Not sure what happens if you have no fork and no write access.

**Comment by benjeffery** [comment]
No fork and no write access ends up making a fork for you automagically.

**Comment by hyanwong** [comment]
@benjeffery - I think you might want to have checked the phrasing before merging (see my comment to @petrelharp above)

**Comment by petrelharp** [comment]
@yanwong want to try automagically fixing it?

**Comment by hyanwong** [comment]
Yes, I can - just want to check I'm not misunderstanding!

**Pull request merged**
