### PR TITLE
added nodes time refactor code

### PR DESCRIPTION
**Pull request by PalashLalwani**
## Description
Refactored code for getting node time as mentioned in issue #2766.

Fixes #(issue) <- #2766

# PR Checklist:

- [ ] Tests that fully cover new/changed functionality.
- [ ] Documentation including tutorial content if appropriate.
- [ ] Changelogs, if there are API changes.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks great, thanks @PalashLalwani!

**Comment by jeromekelleher** [comment]
Build issues are part of current CI malaise I assume @benjeffery?

**Comment by PalashLalwani** [comment]
@jeromekelleher I have requested to review again, build docs is failing.

**Comment by benjeffery** [comment]
I've rebased to get the docs fix, should be good to go.

**Pull request merged**
