### PR TITLE
add_pbs and test

### PR DESCRIPTION
**Pull request by atongsa**
## Description

add a PBS function to test population local adaptation;
solve the issue #2717;

Fixes #(2717) <- Putting the issue number here will auto-close the issue when this PR is merged 

# PR Checklist:

- [x] Tests that fully cover new/changed functionality.
- [ ] Documentation including tutorial content if appropriate.
- [ ] Changelogs, if there are API changes.

### CODE REVIEW

**Comment by atongsa** [comment]
add function and test of pbs

**Comment by jeromekelleher** [comment]
Looks good, thanks @atongsa ! Looks like you're missing the changes for the actual module code in this PR though?

**Comment by benjeffery** [comment]
BTW - you can push your code more than once to a PR - there's no need to create a new one.

**Comment by atongsa** [comment]
ok

**Comment by jeromekelleher** [comment]
Sorry we've been slow to review this PR @atongsa, it's hard to keep up sometimes. We would like to incorporate this statistic, but it will take some more work. Would you mind leaving the PR open please?

**Comment by atongsa** [comment]
> Sorry we've been slow to review this PR @atongsa, it's hard to keep up sometimes. We would like to incorporate this statistic, but it will take some more work. Would you mind leaving the PR open please?

actually, i am sorry
i messed my fork code and delete my  branch, so this pr is closed automately;
can i reopen a new pr

**Pull request closed without merging**
