### PR TITLE
Make default metadata schema dependant

### LINKED ISSUE #1084: Metadata should default to {} on Table.add_row if schema is set
Quite a bit of code breaks when we set a metadata schema because there isn't a useful default for ``metadata`` in ``add_row``, e.g.:
```python
schema = tskit.MetadataSchema({
    "codec": "json",
    "type": "object",
    "properties": {},
    "required": [],
    "additionalProperties": True,
    }
)

tables = tskit.TableCollection(1)
tables.populations.metadata_schema = schema
tables.populations.add_row(metadata={}) # Fine
tables.populations.add_row() # breaks
```

It seems reasonable to add the empty metadata as the default here, when a schema is defined.

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #1084

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM @benjeffery. I'm slightly worried that this ``schema.default_value`` will be confusing when we start thinking about setting defaults, as discussed in #1073. Is it worth looking at this at the same time, since they are closely related?

**Comment by benjeffery** [comment]
My thinking here is that it is not `add_row`'s concern to know what the default value for metadata should be. I think the schema's default metadata value will still be `{}` even after we add `default` functionality for keys. 

Maybe if I rename this attribute to `empty_value` instead?

**Comment by jeromekelleher** [comment]
> Maybe if I rename this attribute to empty_value instead?

yes, good call.

**Comment by benjeffery** [comment]
Ok, I've changed the attribute name. Should be good to go.

**Comment by petrelharp** [comment]
LGTM - but perhaps there should be a note in the documentation about metadata schemas explaining that {} will be passed in if no metadata are provided, so this should be legal for the schema if it's desired to be able to do that.

**Review by jeromekelleher — APPROVED** [review]

**Comment by jeromekelleher** [comment]
Yes, we should have a discussion of default handling. I guess we could add a section to the docs in this PR explaining this much, and then add to it when we have implemented #1073

**Comment by benjeffery** [comment]
I've added a small note to the docs.

**Comment by jeromekelleher** [comment]
I've had a look through the diff, but I'm not seeing any changes to the docs @benjeffery - maybe you forgot to push?

**Comment by benjeffery** [comment]
Should be there now. I only added a note to the `add_row` docstring - we can add a full section about default handling after #1073.

**Comment by benjeffery** [comment]
A pre-commit update is also along for the ride as its cache got in an inconsistent state.

**Pull request merged**
