### PR TITLE
Add c/CMakeLists.txt

### PR DESCRIPTION
**Pull request by lukashuebner**
I've been using this `CMakeLists.txt` using the following code in my code for a while now:

```
add_subdirectory("extern/tskit/c" "extern/tskit")
target_link_libraries(${MY_TARGET} INTERFACE tskit) # ${MY_TARGET} is header-only, thus INTERFACE
```

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Thanks @lukashuebner, this will be really helpful for CMake users!

I wonder if it belongs in the tsk-tbuild-example repo though? It would naturally fit into a ``CMake``subdirectory

https://github.com/tskit-dev/tskit-build-examples

**Comment by lukashuebner** [comment]
Imho, the right place would be in this repo. Otherwise the user would need to maintain a list of `tskit`'s source files, dependencies and build settings themself, which would violate the encapsulation principle. If you prefer the tskit-build-examples repo, though, I can create a PR there.

**Comment by jeromekelleher** [comment]
I see your point @lukashuebner, but I don't really want to get into maintaining multiple build-systems within tskit. We've chosen meson here as the libraries build system, and the specific point of the tskit-build-examples repo is to give examples of how to build applications using tskit using different build systems. As the dev docs say:

> There are many different build systems and approaches to compiling code, and so it’s not possible to give definitive documentation on how tskit should be included in downstream projects. Please see the build examples repo for some examples of how to incorporate tskit into different project structures and build systems.

So, it would be great if you could add this to the build examples for other CMake users!

**Comment by lukashuebner** [comment]
See https://github.com/tskit-dev/tskit-build-examples/pull/7

**Comment by jeromekelleher** [comment]
Great, thanks.

Out of interest, did you realise that we had this build-example repo? How was your experience of getting CMake running, and did you find the dev-docs useful?

**Comment by lukashuebner** [comment]
I created the `CMakeLists.txt` a few months back, so I'm not 100 % sure, but I think I didn't know the repo with the build examples existed. Getting CMake running was pretty straightforward though – your `meson.build` file is easy enough to read and translate to CMake. (I never used Meson and would consider myself an average CMake user.)

**Comment by jeromekelleher** [comment]
Maybe we need to signpost this a bit more prominently, say in the README.md in the c directory? 

Do you build your applications "in tree" here in the tskit source, or do you then install the headers and lib files to your file system somewhere?

**Comment by benjeffery** [comment]
I'm assuming we're not merging this as it went to the example repo - please reopen if that isn't the case.

**Pull request closed without merging**
