### PR TITLE
Refactor ``Variant`` class and associated genotype utility functions

### LINKED ISSUE #2212: Move `Variant` and associated code to `genotypes.py`
Similarly to the C API. We're getting quite a lot more functionality here, would be good to have a separate file for this and the associated internal genotype-utility functions.

### PR DESCRIPTION
**Pull request by szhan**
Fixes #2212

### CODE REVIEW

**Comment by szhan** [comment]
Why isn't ``Variant`` class ``util.Dataclass``?

**Comment by szhan** [comment]
Should the auxiliary function ``allele_remap`` be moved to ``genotypes.py``?

**Comment by jeromekelleher** [comment]
Looks good @szhan - the bit you're missing is updating ``tskit/__init__.py`` to import stuff from this new file.

Good to move the related auxiliary functions in here too.

**Comment by benjeffery** [comment]
> Why isn't `Variant` class `util.Dataclass`?

The benefits of a dataclass are that you get the dunder methods and things like `asdict` for free. I'm not sure what use this would be for `Variant` as it isn't an "attribute storage" class, but a thin wrapper around the CPython Variant class.

**Comment by benjeffery** [comment]
> Should the auxiliary function `allele_remap` be moved to `genotypes.py`?

Yep

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Pull request merged**
