### PR TITLE
Variant copy for lowlevel python

### PR DESCRIPTION
**Pull request by benjeffery**
Stacked on #2157 
Adds `restricted_copy` to the low-level python. I think I've covered all the lifecycle stuff here, but a close review would be appriciated.

### CODE REVIEW

**Comment by benjeffery** [comment]
Note to self - run the stress test for leaks.

**Comment by benjeffery** [comment]
Looks like the linter has broken deps, will investigate.

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by jeromekelleher** [comment]
I can take a look at this once it's rebased @benjeffery

**Comment by benjeffery** [comment]
> Looks right to me, but I'd run some serious stress tests on this sort of thing to reassure myself as it's very subtle.

Stress test is fine, max iter is at 100 after 1000 runs. I've also gone over the code again to try and satisfy myself.

**Review by jeromekelleher — APPROVED** [review]

**Comment by jeromekelleher** [comment]
I'd usually run in a loop in a standalone script as well, as the stress script is quite slow and noisy when checking specific changes like this. Problems usually show up very quickly.

**Pull request merged**
