### PR TITLE
write_vcf plink note

### PR DESCRIPTION
**Pull request by saurabhbelsare**
Added note in write_vcf to deal with conflict default individual names generate with plink

### CODE REVIEW

**Comment by benjeffery** [comment]
Thanks for the PR @saurabhbelsare! Do you think you could add the exact error message that plink produces to the text? I'm thinking about users who might google for an answer. For example ".... at the end of an individual id. This causes plink to error with \`\`..error text here...\`\`"

**Comment by benjeffery** [comment]
Also, you have 2 commits here, would you mind squashing them? Thanks!

**Comment by saurabhbelsare** [comment]
Hi @benjeffery I've made the change in the documentation as you requested. I also tried to squash the commits, but I'm not sure I succeeded. I haven't done this before. Could you let me know if it's worked? If not, I'll try again. Thanks.

**Comment by benjeffery** [comment]
Hmm, I'm not sure why github closed this! I didn't intend for that. Your squash attempt ended up with 4 commits (I think there was a merge in there) and I was pushing to this branch to fix it. I'll open a new PR with the fixed commit and merge.

**Comment by benjeffery** [comment]
All merged in. Thanks for bringing this up and making a PR @saurabhbelsare. If you have any other ideas for improving tskit then let us know.

**Comment by saurabhbelsare** [comment]
Thanks @benjeffery. Sorry for the improper sqashing. I need to figure out how to do it correctly for whenever I need to do this again.

**Pull request closed without merging**
