### PR TITLE
Add tracemalloc output and metadata tests to stress_lowlevel.py

### PR DESCRIPTION
**Pull request by benjeffery**
Running this has identified some possible leaks I'm looking into.

### CODE REVIEW

**Comment by benjeffery** [comment]
I've added tracemalloc to the stress tester, it lists the lines where memory is leaking.

**Comment by jeromekelleher** [comment]
I *love* the curses interface too, great idea!

**Comment by jeromekelleher** [comment]
Merge away whenever.

**Comment by benjeffery** [comment]
I've made it spit out as many lines as there is room for and clear the screen properly between iterations. Will merge now.

**Pull request merged**
