### PR TITLE
add delete_sites table function

### LINKED ISSUE #363: Remove arbitrary sites from a tree sequence
I keep using something like the function below. Should we tidy it up and add it to the API? It seems useful to me (it's also coded up semi-independently as `remove sites` in https://github.com/tskit-dev/tskit/pull/292) 

```python
def prune_sites(ts, keep_sites):
    # Remove sites and mutations not marked as `True` in the keep_sites boolean array
    def keep_with_offset(keep, data, offset):
        """Copied from keep_intervals"""
        # We need the astype here for 32 bit machines
        lens = np.diff(offset).astype(np.int32)
        return (
            data[np.repeat(keep, lens)],
            np.concatenate([
                np.array([0], dtype=offset.dtype),
                np.cumsum(lens[keep], dtype=offset.dtype)]))

    tables = ts.dump_tables()
    sites = ts.tables.sites
    mutations = ts.tables.mutations

    new_as, new_as_offset = keep_with_offset(
        keep_sites, sites.ancestral_state, sites.ancestral_state_offset)
    new_md, new_md_offset = keep_with_offset(
        keep_sites, sites.metadata, sites.metadata_offset)
    keep_mutations = keep_sites[mutations.site]
    tables.sites.set_columns( #replaces existing
        position=sites.position[keep_sites],
        ancestral_state=new_as,
        ancestral_state_offset=new_as_offset,
        metadata=new_md,
        metadata_offset=new_md_offset)

    new_ds, new_ds_offset = keep_with_offset(
        keep_mutations, mutations.derived_state, mutations.derived_state_offset)
    new_md, new_md_offset = keep_with_offset(
        keep_mutations, mutations.metadata, mutations.metadata_offset)

    site_map = np.cumsum(keep_sites, dtype=mutations.site.dtype) - 1
    parent_map = np.cumsum(keep_mutations, dtype=mutations.parent.dtype) - 1
    # parent -1 always maps to parent -1
    parent_map = np.append(parent_map, np.array([-1], dtype=mutations.parent.dtype))
    # Don't bother dealing with connected mutations as we are removing the whole site
    tables.mutations.set_columns(
        site=site_map[mutations.site[keep_mutations]],
        node=mutations.node[keep_mutations],
        derived_state=new_ds,
        derived_state_offset=new_ds_offset,
        parent=parent_map[mutations.parent[keep_mutations]],
        metadata=new_md,
        metadata_offset=new_md_offset)

    return tables.tree_sequence()
```

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #363

### CODE REVIEW

**Comment by hyanwong** [comment]
Do we also want this as a tree sequence function?

I.e. do we want to be able to do `ts_new = ts.delete_sites([1,2,3])` as well as `ts.dump_tables().delete_sites([1,2,3])`?

**Comment by jeromekelleher** [comment]
I've updated this to simplify the interface (it's just adding complexity for no real gain supporting boolean selector arrays) and to add some tests. The existing tests were weak. 

There's a bug to be fixed when we have multiple mutations.

**Comment by hyanwong** [comment]
> I've updated this to simplify the interface (it's just adding complexity for no real gain supporting boolean selector arrays) 

Right

> There's a bug to be fixed when we have multiple mutations.

Do you want me to do this?

**Comment by jeromekelleher** [comment]
> Do you want me to do this?

Yes, if you want  the PR merged.

**Comment by hyanwong** [comment]
This should pass once #366 or equivalent is merged

**Comment by hyanwong** [comment]
Rebased. I think the fact that I got the parent mutations mixed up (I assumed they contained node IDs, not mutation IDs) is a good argument for merging this, rather than relying on people to cook up their own, potentially buggy, equivalent.

**Comment by jeromekelleher** [comment]
OK, I think this is ready to merge. I've added some clarifications on the ordering requirements for IDs (there are none) and what happens when we have duplicate IDs.

**Comment by petrelharp** [comment]
This is great! We will have use for this. :yay:

**Comment by hyanwong** [comment]
@petrelharp - great. I think some of the code in keep_intervals / delete_intervals might be simplified by calling this function too, if we want to reduce code duplication.

**Pull request merged**
