### PR TITLE
Cache some test functions to speed up tests

### PR DESCRIPTION
**Pull request by jeromekelleher**
This should knock another 30 seconds or so off the test suite runtime. I haven't looked to see if there are any more of these we can cache, will update later.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I can't find any other low-hanging fruit here, barring a significant update to the test_tree_stats file I don't think we'll do much better. This is a major improvement though.

**Review by benjeffery — APPROVED** [review]
LGTM, but I'm getting very little benefit, maybe 1-2s. I guess this works better singly threaded?

**Comment by jeromekelleher** [comment]
Ah - well, it's no harm anyway.

**Comment by molpopgen** [comment]
Is it possible for the caching to be a race condition when running tests in parallel?

**Comment by benjeffery** [comment]
> Is it possible for the caching to be a race condition when running tests in parallel?

Don't think so, as the parallel tests run in separate processes, likely why there is less benefit as the cache is not shared.

**Comment by molpopgen** [comment]
> > Is it possible for the caching to be a race condition when running tests in parallel?
> 
> Don't think so, as the parallel tests run in separate processes, likely why there is less benefit as the cache is not shared.

Right forgot about that.  Although they are ugly, that's exactly why session wide fixtures exist in pytest.

**Pull request merged**
