### PR TITLE
remove 1/2 in branch AFS: closes #2925

### LINKED ISSUE #2925: Folded AFS between branch and site modes differs by factor of two
The following is a little unintuitive to me:
```python
import msprime
import numpy as np

mu = 1e-8
ts = msprime.sim_ancestry(
    samples=10,
    recombination_rate=1e-8,
    sequence_length=1e6,
    population_size=1e4,
)
ts = msprime.sim_mutations(ts, rate=mu)

ss_site = ts.segregating_sites()
ss_branch = ts.segregating_sites(mode='branch') * mu
afs_site = np.sum(ts.allele_frequency_spectrum(polarised=True))
afs_branch = np.sum(ts.allele_frequency_spectrum(mode='branch', polarised=True) * mu)
foldafs_site = np.sum(ts.allele_frequency_spectrum(polarised=False))
foldafs_branch = np.sum(ts.allele_frequency_spectrum(mode='branch', polarised=False) * mu)

print(f"Ratio of site to branch, segsites: {ss_site/ss_branch}")
print(f"Ratio of site to branch, sum(AFS): {afs_site/afs_branch}")
print(f"Ratio of site to branch, sum(folded AFS): {foldafs_site/foldafs_branch}")

# Ratio of site to branch, segsites: 1.0018654284984811
# Ratio of site to branch, sum(AFS): 1.0018654284984798
# Ratio of site to branch, sum(folded AFS): 2.0037308569969605
```
the entries of the branch-mode folded AFS are a factor of 2 from the site-mode folded AFS ... Shouldn't `mode='branch'` give the expectation exactly here; like it does for segregating sites and the unfolded AFS?

### PR DESCRIPTION
**Pull request by petrelharp**
Note also the (fairly cursory) tests that (a) fold(branch AFS) == (branch AFS, unpolarised) and (b) the same is true for site AFS with infinite-sites.

### CODE REVIEW

**Comment by petrelharp** [comment]
I think this is ready to go!

**Comment by jeromekelleher** [comment]
LGTM - we should update the CHANGELOG though, or we'll forget.

**Comment by petrelharp** [comment]
Done. I see codecov is still weird, but I think it's safe to merge this.

**Comment by jeromekelleher** [comment]
Yep, happy to merge.

What's going on with the cache thing in MacOS @benjeffery?

**Comment by petrelharp** [comment]
It seems to be lowering coverage slightly because it's just reduced the denominator. I'll let you hit merge, since I'm not sure if merging PRs where CI failed has undesired effects?

**Comment by benjeffery** [comment]
Looks like something has changed in the osx base image? Will look into it.

**Comment by benjeffery** [comment]
> Done. I see codecov is still weird, but I think it's safe to merge this.

Note that https://github.com/tskit-dev/tskit/issues/2931 is ongoing.

**Comment by benjeffery** [comment]
@mergifyio rebase

**Review by jeromekelleher — APPROVED** [review]

**Pull request merged**
