### PR TITLE
Switch python c module to use C99 initialisers

### LINKED ISSUE #77: Change Python C module to use C99 style initialisers
Change the struct initialisers in ``_tskitmodule.c`` to use the [recommended](
https://docs.python.org/3.6/extending/newtypes_tutorial.html#the-basics) c99 style initialisers. Eg, a Type definition would look like:

```C
static PyTypeObject LdCalculatorType = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "_tskit.LdCalculator",
    .tp_doc = "LdCalculator objects.",
    .tp_basicsize = sizeof(LdCalculator),
    .tp_itemsize = 0,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_new = PyType_GenericNew,
    .tp_init = (initproc) LdCalculator_init,
    .tp_dealloc = (destructor) LdCalculator_dealloc,
    .tp_methods = LdCalculator_methods,
    .tp_members = LdCalculator_members,
};
```

Also remove the ``-Wno-missing-field-initializers`` compiler flag from the Makefile and Circle CI compiler step. 

There may be issues with portability, so this should not be done until CI on Appveyor and Travis have been fully enables (see #41).

Good starter issue for someone looking to understand the Python C API a little better.

### PR DESCRIPTION
**Pull request by benjeffery**
Closes #77

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/tskit-docs/901/)

**Comment by petrelharp** [comment]
I don't know anything about this, but I'm happy to approve it if you think I should?

**Comment by benjeffery** [comment]
@petrelharp It's no new functionality and no changes to tests, so probably safe to approve! I'd usually ask KT for things like this in JKs absence, but he said a few days back he was swamped with teaching.

**Comment by petrelharp** [comment]
I don't see anything wrong, and it seems a matter of style? So, ok?

**Review by petrelharp — APPROVED** [review]

**Comment by benjeffery** [comment]
It's mostly so that we can turn back on some compiler warnings.

**Pull request merged**
