### PR TITLE
Add 'mid' property to Interval class

### PR DESCRIPTION
**Pull request by currocam**
## Description

Add mid property to the Interval and Tree class, as requested in #2903

# PR Checklist:

- [x] Tests that fully cover new/changed functionality.
- [x] Documentation including tutorial content if appropriate.
- [x] Changelogs, if there are API changes.

### CODE REVIEW

**Comment by currocam** [comment]
ci/circleci: build-32  and  codecov/project don't pass, but I don't know how those errors are related with my PR

**Comment by petrelharp** [comment]
Hm - well, there's currently just one test, but two methods added (although one calls the other). Perhaps add another test for the Interval property (so it is tested autonomously)? The CI failures might be just transient.

**Comment by currocam** [comment]
Hi, 
I just added the second test! Thank you for reviewing the changes

And for making such amazing piece of software! I've used a lot doing my master's thesis and I hope I will keep doing after I finish :)

**Review by jeromekelleher — APPROVED** [review]
LGTM, thanks @currocam!

Before we merge we'll need to rebase and squash the commits, but probably better to wait until after #2961 is done first (the changelog will be confusing otherwise)

**Comment by jeromekelleher** [comment]
Looks like you have a few lint issues that need to be fixed also.

**Comment by jeromekelleher** [comment]
Thanks @currocam! It's probably worth installing pre-commit, following the dev docs [here](https://tskit.dev/tskit/docs/stable/development.html#pre-commit-checks). (pre-commit install, should do it).

It would be good to rebase and squash the commits also, as this is a small change. This [guide](https://popsim-consortium.github.io/stdpopsim-docs/stable/development.html#rebasing) may be helpful.

**Comment by currocam** [comment]
Hi! Thank you very much! 
I was in fact of the process of install pre-commit, thanks for pointing that out!

**Comment by jeromekelleher** [comment]
Great, looks ready to merge 👍

**Comment by benjeffery** [comment]
@mergifyio rebase

**Pull request merged**
