### PR TITLE
Fix copyright

### LINKED ISSUE #2179: Update copyright notices for C
Most files in the C API should be updated to 2022.

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #2179

### CODE REVIEW

**Comment by benjeffery** [comment]
Yes, checks if the file is staged first, as then the year need to be this year, else checks the git log for that file. It's a bit rough and ready but let's see if it works for a while. It could auto-write to the file, but it got late! If it is annoying enough to manual change I might do that another day.

**Comment by jeromekelleher** [comment]
I don't think it's worth auto-writing, it'll happen quite rarely and it's an easy update to make. It's a nice helpful bit of automation.

**Comment by benjeffery** [comment]
@mergifyio refresh

**Comment by petrelharp** [comment]
Woah!

**Comment by benjeffery** [comment]
> Woah!

🤓 I lost too many review-golf games to this, no longer!

**Pull request merged**
