### PR TITLE
Build wheels in github action

### LINKED ISSUE #636: Automated release infrastructure
Port automated release infrastructure from kastore to here.

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #636

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks good, thanks @benjeffery. We should probably verify that the oldest-numpy thing works over in kastore first before bringing this in, though?

**Comment by benjeffery** [comment]
Yep, will sort that out over at kastore first.

**Comment by benjeffery** [comment]
@jeromekelleher Ready for review, getting testing working was a small fix in the end. Only needed change now is removing the triggering on PRs, but will do that when I squash so you can see the actions.

**Comment by benjeffery** [comment]
The full test are prob overkill, but the import test at least catches things like https://github.com/tskit-dev/msprime/pull/1031 
Squashed and PR trigger removed, marking for merge.

**Comment by benjeffery** [comment]
Mergify can't merge changes to github actions.

**Pull request merged**
