### PR TITLE
Avoid copy in tsk_treeseq_simplify

### LINKED ISSUE #2287: Add TSK_TAKE_OWNERSHIP in tsk_treeseq_simplify
We can easily avoid an extra table copy in ``tsk_treeseq_simplify``, we just need to pass ownership of the local tables to tsk_treeseq_init and stop freeing the tables at the end of the method.

This is a reasonbly significant memory optimisation, so might as well get it in ASAP.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Closes #2287

### CODE REVIEW

**Review by benjeffery — APPROVED** [review]
LGTM! Great!

**Comment by petrelharp** [comment]
Whoah, this is very nice. This should help SLiM, @bhaller! (once I merge the final tskit C_1.0 in).

**Comment by bhaller** [comment]
> Whoah, this is very nice. This should help SLiM, @bhaller! (once I merge the final tskit C_1.0 in).

Nice!  I wasn't aware this was happening, looks helpful indeed.

**Comment by jeromekelleher** [comment]
> This should help SLiM, @bhaller! (once I merge the final tskit C_1.0 in).

I'd be surprised if it makes any difference for SLiM, since I'd imagine you guys are calling ``tsk_table_collection_simplify`` rather than ``tsk_treeseq_simplify``.

**Comment by bhaller** [comment]
> > This should help SLiM, @bhaller! (once I merge the final tskit C_1.0 in).
> 
> I'd be surprised if it makes any difference for SLiM, since I'd imagine you guys are calling `tsk_table_collection_simplify` rather than `tsk_treeseq_simplify`.

Ah!  That is true, we are.

**Pull request merged**
