### PR TITLE
Add `pair_coalescence_counts` method

### PR DESCRIPTION
**Pull request by nspope**
Reprise of #2915

### CODE REVIEW

**Comment by jeromekelleher** [comment]
@benjeffery any idea what's going on with codecov here?

**Comment by jeromekelleher** [comment]
Would it help to merge a small PR which doesn't do much to try and reset codecov's view of HEAD?

**Comment by nspope** [comment]
The Codecov uploads are failing with:

> [2024-04-10T04:25:12.526Z] ['verbose'] The error stack is: Error: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}

Looks like this has been cropping up [elsewhere](https://github.com/codecov/codecov-action/issues/1359)?

**Comment by nspope** [comment]
FWIW it sounds like bumping the codecov-action version from 3 to 4 may fix the issue:

https://github.com/tskit-dev/tskit/blob/9e1bf0d99746093d66f1e435301ac901d2795d13/.github/workflows/tests.yml#L159

**Comment by benjeffery** [comment]
> FWIW it sounds like bumping the codecov-action version from 3 to 4 may fix the issue:
> 
> https://github.com/tskit-dev/tskit/blob/9e1bf0d99746093d66f1e435301ac901d2795d13/.github/workflows/tests.yml#L159
> 
> there's a blurb in the v4 notes [here](https://github.com/codecov/codecov-action),
> 
> > v3 versions and below will not have access to CLI features (e.g. global upload token, ATS).

Will try that - thanks for the pointer.

**Comment by nspope** [comment]
Closing in favor of #2915

**Pull request closed without merging**
