### PR TITLE
Fix coverage and add lwt coverage

### PR DESCRIPTION
**Pull request by benjeffery**
Fix flags and add new flag.

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/tskit-docs/970/)

**Review by jeromekelleher — APPROVED** [review]
Nice, thanks for sorting this out. It's probably been broken for a while.

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by benjeffery** [comment]
> Nice, thanks for sorting this out. It's probably been broken for a while.

I think I probably broke it, so my bad!

**Pull request merged**
