### PR TITLE
Copy samples when copying a variant to fix segfault when copy.samples is accessed

### LINKED ISSUE #2400: Segfault on accessing variant.samples
This segfaults for me, and I think it does on CI too.

```python
import msprime
ts = msprime.simulate(10, mutation_rate=1)
next(ts.variants()).samples
```

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #2400

### CODE REVIEW

**Comment by molpopgen** [comment]
I can take a peek later today!

**Comment by molpopgen** [comment]
I don't see any obvious red flags in the changes to the C side.  But I may not be the best person to find them.

I ran this, which didn't flag anything relevant to these diffs:

```sh
find tskit -name '*.c' | xargs clang-tidy -p build/compile_commands.json --checks="all"
```

**Comment by benjeffery** [comment]
Thanks @molpopgen!

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by benjeffery** [comment]
Merging without an approval as @jeromekelleher is away and we need to push out a fix.

**Pull request merged**
