### PR TITLE
AFS docs

### PR DESCRIPTION
**Pull request by petrelharp**
I got confused about the output of some AFS, and worked out what's going on.

### CODE REVIEW

**Comment by petrelharp** [comment]
To be clear - I'm asking for input mostly on whether what I've written is clear, not whether what I describe is the right thing to compute for the AFS - we've discussed that extensively elsewhere (although it might not be), but in any case is a question for a different thread.

**Comment by molpopgen** [comment]
I think that this reads very well.  I'd say that this section would need a careful reading by anyone, but that's the nature of the problem.  Pictures may help, but I am totally fine with what you have written here.

**Comment by petrelharp** [comment]
> and I think that the treatment of the data is correct.

*phew!* =)

**Comment by petrelharp** [comment]
> I made my comments in the main thread for the PR.

I don't see any comments?

**Comment by molpopgen** [comment]
> I don't see any comments?

hmmm--reload?  I just said that I liked it ;)

**Comment by molpopgen** [comment]
This is the comment: https://github.com/tskit-dev/tskit/pull/590#issuecomment-625944221

**Comment by petrelharp** [comment]
Oh, I saw that one. =)

**Pull request merged**
